title: Aaron Brady
email: aaron@insom.me.uk
description: >-
  Usury is evil.
baseurl: ""
url: "https://www.insom.me.uk"

theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
